### ISSUE TITLE
Link is broken.

### ISSUE THREAD

**Issue by marshallgallatin** [minbi/cs371p-blog#1]
Hey, I'm in your CS371p class at UT.

The link in your [week 3 blogpost](http://minbi.github.io/Bloggity/weekly/2015/09/13/week3.html) is broken.

You don't need the site url in your link unless you are linking to your own site.

This:
`[There is hope.]({{ site.url }}https://help.github.com/articles/remove-sensitive-data/)`

Should become this:
`[There is hope.](https://help.github.com/articles/remove-sensitive-data/)`

**Comment by minbi** [comment]
Thanks
